Attribute VB_Name = "modInitVariables"
Option Explicit

'''''''''''''''''''Root Direct X Object''''''''''''''''''''''
Public DX As New DirectX8                                   '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

'''''''''''''''''''''''Direct Sound''''''''''''''''''''''''''
'Sets up a Direct sound ojbect for each sound card/board.   '
Public clsDS1 As New clsDirectSound8                        '
'Now The Direct Sound Secondary Buffer Object               '
Public clsDSB1 As New clsDSSBuff8                           '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

''''''''''''''''''''''Direct Capture'''''''''''''''''''''''''
'Create The Direct Capture Object                           '
Public clsDSC1 As New clsDirectCapture8                     '
'Now The Direct Sound Capture Buffer Object                 '
Public clsDSCB1 As New clsDSCBuff8                          '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

''''''''''''''''''''Enumirator for Capture Devices'''''''''''
'This Structure Holds Values That Pretain To Card Properties'
'Currently On Ur System. Such As How Many, Their GUID(Global'
'Unique Identifier) Numbers.  That Kinda Stuff. Its Going To'
'Tell me how many sound and capture devices i have.         '
'One For Sound                                              '
Public DSEnum As DirectSoundEnum8                           '
'And One For Capture                                        '
Public DSCEnum As DirectSoundEnum8                          '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

'''''''''''''''''''''''''''Boards''''''''''''''''''''''''''''
'These Variables are either True or False, They will show   '
'weather there is a board present on the box or not.        '
Public blnSoundBoard1 As Boolean                            '
Public blnCaptureBoard1 As Boolean                          '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
            
'Some Program Variables''''''''''''''''''''''''''''''''''''''
Public CBFormat As WAVEFORMATEX                             '
Public CaptureCaps As DSCCAPS                               '
                                                            '
Public DSCDesc As DSCBUFFERDESC                             '
Public DSDesc As DSBUFFERDESC                               '
                                                            '
'Public DSCCurs As DSCURSORS                                 '
'Public DSCurs As DSCURSORS                                  '
                                                            '
Public RecLCP1 As Long                                      '
Public bCaptureRunning1 As Boolean                          '
Public bSoundRunning1 As Boolean                            '
Public bStartRec1Click As Boolean                           '
Public bStopRec1Click As Boolean                            '
Public Buffer() As Byte                                     '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
